### ISSUE TITLE
Visual Studio?

### ISSUE THREAD

**Issue by CatalinRadoi** [blackbirdtheme/vscode#14]
Hi Matt!

Can you make blackbird available for Visual Studio (not Visual Studio Code!)?
_(I am currently using version 2022 Preview)_

_Not everyone uses Visual Studio Code. If you're a C# dev, VS is way way way better than VSCode ;)_

Thanks!

**Comment by gleich** [comment]
Hey @CatalinRadoi! As this is just a personal project I've only created themes for tools/editors that I personally use. I don't have access to and have never used Visual Studio so I'm not super sure that I could create one. Lemme know if you would be interested in creating one and I'll crack open a new repo for you to work in :)
