### ISSUE TITLE
as per your experience using this theme, is following true?

### ISSUE THREAD

**Issue by j33l** [blackbirdtheme/vscode#15]
"lack of background light around texts makes it stressful to read and focus on text, high contras theme and all are just for power saving for mled and similar displays."

personally i never used this much darker theme, what r your opinions if u r using this daily...

**Comment by gleich** [comment]
I've personally never had any problems with the pitch-black background just because I tend to keep my display's brightness high. I do plan to make a light theme version so hopefully that will help anyone that is having this problem!
