### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by SrWildman** [blackbirdtheme/vscode#16]
Love the theme for VS code and want to install it. Do you have any details on how to get it installed? Great work!

**Comment by gleich** [comment]
Hey @SrWildman! If you just go to https://marketplace.visualstudio.com/items?itemName=MattGleich.theme-blackbird and click the green install button it should open it in vscode and install it. Hopefully, this helps! I'll add some clearer instructions soon.

**Comment by SrWildman** [comment]
Thank you!
