### ISSUE TITLE
HTML/Vue template syntax colors don't match JSX syntax colors

### ISSUE THREAD

**Issue by jasontheiler** [blackbirdtheme/vscode#17]
Hi Matt,

I work a lot with Vue and other generic HTML templates, so having the regular HTML/Vue template syntax colors not matching the JSX syntax colors is kinda annoying.

JSX:

![JSX](https://user-images.githubusercontent.com/50220557/124782242-5dd5e080-df44-11eb-8528-bb4d49b6b796.png)

HTML/Vue template:

![HTML/Vue template](https://user-images.githubusercontent.com/50220557/124782396-7cd47280-df44-11eb-8f9d-38678fd30689.png)

I forked the repo and tried to add the scope `punctuation.separator.key-value.html` to your `"Red"` syntax color. That successfully turned the `:`, `@` and `=` symbols red. But I don't know how to turn the HTML tag end `/>` gray properly, as the `/` doesn't really have any other useful scope other than `meta.tag.block.any.html`. In Vue templates this also turns the `=` symbol of regular attributes and the arrow and regular function `()` gray, though...

With the aforementioned changes, it would look like this:

![vue-html-2](https://user-images.githubusercontent.com/50220557/124783799-9de99300-df45-11eb-9abf-5df66143ba53.png)

Maybe you have an idea on how to fix it. But I'd also understand if this isn't in your interest anyway 😅

**Comment by gleich** [comment]
Hey, Jason! I'll take a look at this by the end of the day :)

**Comment by gleich** [comment]
Hey Jason! Would you mind making a PR of the work you have done so far and send me a small Vue snippet to play with? Thanks!

**Comment by gleich** [comment]
So I removed `"meta.tag.block.any.html"` on line 301 and the end tag for `AppButton` seems to still work. I've never used Vue before so lemme know if the file I have in the screenshot below isn't valid. Is it possible that you have some extension installed that could be breaking it? It would be super helpful if you could send me a screenshot of your editor inspector tokens when your cursor is on the closing tag. The second image shows mine.

<img width="450" alt="Screen Shot 2021-07-10 at 2 24 50 PM" src="https://user-images.githubusercontent.com/43759105/125172973-9830bf00-e18a-11eb-81d9-3304f318d597.png">
<img width="566" alt="Screen Shot 2021-07-10 at 2 26 32 PM" src="https://user-images.githubusercontent.com/43759105/125173020-d4641f80-e18a-11eb-9452-ec4f69af3e30.png">
