### ISSUE TITLE
What is the font used in this image!

### ISSUE THREAD

**Issue by Drakenlords** [blackbirdtheme/vscode#18]
![image](https://user-images.githubusercontent.com/42362146/124978114-57f10580-dfff-11eb-8b83-8d1e136c4049.png)

what is the font used in this image!

**Comment by gleich** [comment]
Hey @Drakenlords! That is a font called [Victor Mono](https://github.com/rubjo/victor-mono) which is free and open-source on GitHub! I have in the SemiBold variant with ligatures on. If you wanna see how I configured my vscode to look exactly like that I have my [settings.json file](https://github.com/gleich/dots/blob/main/matt/Library/Application%20Support/Code%20-%20Insiders/User/settings.json) open-sourced here on GitHub. Hopefully, this helps!
