### ISSUE TITLE
Hard to say which I am

### ISSUE THREAD

**Issue by shirobachi** [blackbirdtheme/vscode#20]
Hi, I wanna kindly ask if it's possible to make active tab somehow easier to recognizer. For me, the only way is to check with has closing x. If I have 10 tabs open or more, it's very hard to do that.

Anyway it's very nice theme, so thanks for that :)

**Comment by gleich** [comment]
Hello @Shirobachi! At the moment there is a blue bar above the currently active tab that I use to find it. Do you not see this?

<img width="326" alt="Screen Shot 2021-07-26 at 10 21 43 PM" src="https://user-images.githubusercontent.com/43759105/127084894-7acb3a14-4757-4e60-abed-65166817fa8d.png">

I just changed it so the background color of the active border is a bit brighter. Is this better?

![Screen Shot 2021-07-26 at 10 22 54 PM](https://user-images.githubusercontent.com/43759105/127085001-5dd13ab8-1ab2-49d7-8f03-e4a2116a8038.png)

**Comment by shirobachi** [comment]
No, it how I see: 
![image](https://user-images.githubusercontent.com/16509749/127119652-b5875d4e-4fc0-479c-9c65-b4984c8080cd.png)

**Comment by gleich** [comment]
Hey @Shirobachi! I just made a new release which should help with this issue. Lemme know if it is still hard to tell!

**Comment by shirobachi** [comment]
Can I kindly ask for screenshot? I don't see any changes and not sure if I did something wrong .. Anyway thanks :)

**Comment by gleich** [comment]
No problem! Ya, see how the active tab is brighter now? Probably not a good sign if you can't see it lol.

<img width="295" alt="Screen Shot 2021-07-29 at 10 56 48 PM" src="https://user-images.githubusercontent.com/43759105/127593005-8cdefc1d-9686-42df-aa35-3fe2be772ee8.png">

**Comment by gleich** [comment]
I'll look at adding a border color if you can't see it.

**Comment by shirobachi** [comment]
Hmmm so I am doing something wrong... That's how I see that
![image](https://user-images.githubusercontent.com/16509749/127593383-1728e44c-024b-4eb7-9ca0-7a482c2df460.png)
I uninstalled and installed again your extension, do you think that it can happen because I use linux (ubuntu with i3 as wm)

**Comment by gleich** [comment]
Oh yeah, it is working fine. I'll add a border rn. Gimme a few

**Comment by gleich** [comment]
@Shirobachi so if you could make the tab color on the top black inside of white it would be easier to see the blue bar that already exists. I tried to find a good way to make it more visible but I can't seem to find any good solutions. I've personally never had a problem with active tab identification as this is what it looks like on my machine: 

<img width="471" alt="Screen Shot 2021-07-29 at 11 18 49 PM" src="https://user-images.githubusercontent.com/43759105/127594719-7e2f2297-c40a-4737-abc6-6c53ebb070ae.png">

As you can see `.vscodeignore` is clearly highlighted as the current tab. Sorry if this isn't very helpful!

**Comment by shirobachi** [comment]
TBH I don't know how to do that ;/ I never changed anything like that ( except installing themes ) I'll google it in free time! 


Thanks for your help!

**Comment by shirobachi** [comment]
Just for future ppl I used following settings
```
    "workbench.colorCustomizations": {
      "tab.activeBackground": "#148ee3",
      "tab.activeForeground": "#000",
    },
```
It changes whole background what work for me, for some ppl following line would be enough
```
    "workbench.colorCustomizations": {
      "tab.activeBorder": "#148ee3",
    },
```
This in my case would add a border on the bottom of active tab



Thanks for your help and great theme!
